name: Curse Build

on:
  push:
    branches:
    - main
    tags:
    - '*'

    paths-ignore:
    - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: BigWigsMods/packager@master
      with:
        args: -p 6124 -a kRNL70Go -g bcc
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
